<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dhbw.trasima</groupId>
        <artifactId>trasima</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>trasima-aufgabe02</artifactId>
    <packaging>jar</packaging>

    <name>Trasima Aufgabe Nr.02</name>

    <dependencies>
        <!-- Add dependencies specific to this module -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
        </plugins>
    </build>
</project>